apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: flink-kubernetes-operator
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T05:07:21Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: flink-kubernetes-operator-1.7.0
  name: flink
  namespace: default
  resourceVersion: "797"
  uid: 33fde0c0-1fd8-450f-a981-a2449adab6f3
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - '*'