---
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
#    org.springframework.web.socket: TRACE

application:
  client-origin-url: ${CLIENT_ORIGIN_URL}

server:
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: src/main/resources/keystore/baeldung.p12
#    key-store-password: 123Htess
#    key-alias: baeldung
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}
  other:
    client-id: ${OKTA_OAUTH2_CLIENT_ID}
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET}
    domain: ${OKTA_OAUTH2_DOMAIN}
...
